version: "3.3"

services: 
  user-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    ports: 
      - "1400:1433"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456789@abc"