-- Quốc Gia
INSERT QUOCGIA(TEN_QUOCGIA) VALUES('Vietnam')
INSERT QUOCGIA(TEN_QUOCGIA) VALUES('China')

-- Thanh phố
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('1','TP.HCM')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('1','Ha Noi')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('1','Hue')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('1','Da Nang')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('1','Ha Long')

INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('2','Guangzhou')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('2','Chongqing')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('2','Sanghai')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('2','Beijing')
INSERT THANHPHO(ID_QUOCGIA,TEN_THANHPHO) VALUES('2','Tianjin')

-- Quận
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('1','District 1')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('1','District 4')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('1','District 11')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('2','Bac Tu Liem District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('2','Ba vi District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('2','Cau Giay District')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('3','Phu Loc District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('3','Nam Dong District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('3','Huong Tra Town')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('4','Son Tra District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('4','Cam Le District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('4','Lien Chieu District')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('5','Tien Yen District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('5','Dam Ha District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('5','Ba Che District')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('6','Erlong Residential District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('6','Nanhuaxi Residential District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('6','Haizhuang Residential District')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('7','Nanchuan District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('7','Yuanba')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('7','Xinqiao')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('8','Dapuqiao Residential District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('8','Wuli Bridge Residential District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('8','Laoximen Residential District')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('9','Qianmen Residential District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('9','Dashilan Residential District')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('9','Chunsu Residential District')

INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('10','Huozhuangzi')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('10','Jizhuangzicun')
INSERT QUAN(ID_THANHPHO,TEN_QUAN) VALUES('10','Xinhouzhuangcun')





