--TAI KHOAN
INSERT INTO TAIKHOAN(TEN_TAIKHOAN,MATKHAU,ROLE_TAIKHOAN) VALUES('a@gmail.com','123456','Partner')
INSERT INTO TAIKHOAN(TEN_TAIKHOAN,MATKHAU,ROLE_TAIKHOAN) VALUES('b@gmail.com','123456','Partner')
INSERT INTO TAIKHOAN(TEN_TAIKHOAN,MATKHAU,ROLE_TAIKHOAN) VALUES('c@gmail.com','123456','Partner')
INSERT INTO TAIKHOAN(TEN_TAIKHOAN,MATKHAU,ROLE_TAIKHOAN) VALUES('d@gmail.com','123456','Partner')
INSERT INTO TAIKHOAN(TEN_TAIKHOAN,MATKHAU,ROLE_TAIKHOAN) VALUES('e@gmail.com','123456','Partner')

--THONG TIN CHU HO
INSERT INTO THONGTINCHUHO(TEN_CHUHO,EMAIL,PHONE_NUMBER,MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,MASO_THUE,ID_TAIKHOAN) 
VALUES('Huynh Thao', 'a@gmail.com','0988767889','0989886','CCCD','Vietnam',1,'23 Ly Chieu Hoang', '11112234',1)
INSERT INTO THONGTINCHUHO(TEN_CHUHO,EMAIL,PHONE_NUMBER,MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,MASO_THUE,ID_TAIKHOAN) 
VALUES('Tran Nhi', 'b@gmail.com','0988767889','0989886','CCCD','Vietnam',1,'23 Ly Chieu Hoang', '11112234',2)
INSERT INTO THONGTINCHUHO(TEN_CHUHO,EMAIL,PHONE_NUMBER,MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,MASO_THUE,ID_TAIKHOAN) 
VALUES('Mac Linh', 'c@gmail.com','0988767889','0989886','CCCD','Vietnam',1,'23 Ly Chieu Hoang', '11112234',3)
INSERT INTO THONGTINCHUHO(TEN_CHUHO,EMAIL,PHONE_NUMBER,MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,MASO_THUE,ID_TAIKHOAN) 
VALUES('Lam Oanh', 'd@gmail.com','0988767889','0989886','CCCD','Vietnam',1,'23 Ly Chieu Hoang', '11112234',4)

--STATE APARTMENT
INSERT INTO TRANGTHAINHA(TEN_TRANGTHAI) VALUES('Unactive')
INSERT INTO TRANGTHAINHA(TEN_TRANGTHAI) VALUES('Active')
INSERT INTO TRANGTHAINHA(TEN_TRANGTHAI) VALUES('Hired')


--STYLE APARTMENT
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Hotel')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Hostel')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Villa')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Resort')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Apartment')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Bed and Breakfast')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Camp')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Boat House')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Homestay')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Guest House')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Ryokan')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Riad')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Service Apartment')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Capsule Hotel')
INSERT INTO LOAINHA(TEN_LOAINHA) VALUES('Homes')

--APARTMENT
INSERT INTO NHA(ID_NHA,ID_TT_CHUHO,ID_LOAINHA,TEN_NHA,FREE_CANCEL,CHECKIN,CHECKOUT,KHOANGCACH_TRUNGTAMTP,SOTANG,PHUPHI_BUASANG,SONHA,TEN_DUONG,DIENTICH,ID_QUAN,SO_NGUOI,SO_GIUONGPHU,GIA,KHUYENMAI,ID_TRANGTHAI_NHA)
VALUES('AAA-01',3,1,'Sunhouse','true','07:00:00','14:00:00',34,2,0,'23','New York',56,1,3,0,350000,0,1)
INSERT INTO NHA(ID_NHA,ID_TT_CHUHO,ID_LOAINHA,TEN_NHA,FREE_CANCEL,CHECKIN,CHECKOUT,KHOANGCACH_TRUNGTAMTP,SOTANG,PHUPHI_BUASANG,SONHA,TEN_DUONG,DIENTICH,ID_QUAN,SO_NGUOI,SO_GIUONGPHU,GIA,KHUYENMAI,ID_TRANGTHAI_NHA)
VALUES('AAA-02',4,1,'New Life','true','07:00:00','14:00:00',34,2,0,'23','New York',56,1,3,0,350000,0,1)
INSERT INTO NHA(ID_NHA,ID_TT_CHUHO,ID_LOAINHA,TEN_NHA,FREE_CANCEL,CHECKIN,CHECKOUT,KHOANGCACH_TRUNGTAMTP,SOTANG,PHUPHI_BUASANG,SONHA,TEN_DUONG,DIENTICH,ID_QUAN,SO_NGUOI,SO_GIUONGPHU,GIA,KHUYENMAI,ID_TRANGTHAI_NHA)
VALUES('AAA-03',2,1,'Happy','true','07:00:00','14:00:00',34,2,0,'23','New York',56,1,3,0,350000,0,1)
INSERT INTO NHA(ID_NHA,ID_TT_CHUHO,ID_LOAINHA,TEN_NHA,FREE_CANCEL,CHECKIN,CHECKOUT,KHOANGCACH_TRUNGTAMTP,SOTANG,PHUPHI_BUASANG,SONHA,TEN_DUONG,DIENTICH,ID_QUAN,SO_NGUOI,SO_GIUONGPHU,GIA,KHUYENMAI,ID_TRANGTHAI_NHA)
VALUES('AAA-04',2,1,'Birthday','true','07:00:00','14:00:00',34,2,0,'23','New York',56,1,3,0,350000,0,1)
INSERT INTO NHA(ID_NHA,ID_TT_CHUHO,ID_LOAINHA,TEN_NHA,FREE_CANCEL,CHECKIN,CHECKOUT,KHOANGCACH_TRUNGTAMTP,SOTANG,PHUPHI_BUASANG,SONHA,TEN_DUONG,DIENTICH,ID_QUAN,SO_NGUOI,SO_GIUONGPHU,GIA,KHUYENMAI,ID_TRANGTHAI_NHA)
VALUES('AAA-05',3,1,'To','true','07:00:00','14:00:00',34,2,0,'23','New York',56,1,3,0,350000,0,1)
INSERT INTO NHA(ID_NHA,ID_TT_CHUHO,ID_LOAINHA,TEN_NHA,FREE_CANCEL,CHECKIN,CHECKOUT,KHOANGCACH_TRUNGTAMTP,SOTANG,PHUPHI_BUASANG,SONHA,TEN_DUONG,DIENTICH,ID_QUAN,SO_NGUOI,SO_GIUONGPHU,GIA,KHUYENMAI,ID_TRANGTHAI_NHA)
VALUES('AAA-06',2,1,'Me','true','07:00:00','14:00:00',34,2,0,'23','New York',56,1,3,0,350000,0,1)